# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Página principal | Pelotero S.A.
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, ../bootstrap/css/bootstrap.css, ../bootstrap/css/default.css]

  javascripts:    [../bootstrap/js/bootstrap.js, ../bootstrap/js/twitter-bootstrap-hover-dropdown.min.js, ../bootstrap/js/jquery.js]

  has_layout:     true
  layout:         layout
